# include common properties for every profile in this section

server.port: 8080
logging:
    level:
        root: INFO
        org.gvamosi.wrapping.*: DEBUG

---
spring:
  profiles:
    active:
#     - local
#     - dev
     - test

---
spring:
    config:
        activate:
            on-profile: test
name: test-YAML
environment: testing
enabled: false
server.port: 8080
servers: 
    - www.abc.test.com
    - www.xyz.test.com

---
spring:
    config:
        activate:
            on-profile: local
name: local-YAML
environment: local
enabled: true
server.port: 8080
servers: 
    - www.abc.local.com
    - www.xyz.local.com

---
spring:
    config:
        activate:
            on-profile: dev
name: application-dev
environment: dev
enabled: true
